- hosts: all
  tasks:
  - file:
       state: directory
       path: "/dvd1"

  - mount:
       src: "/dev/cdrom"
       path: "/dvd1"
       state: mounted
       fstype: "iso9660"

  - yum_repository:
       baseurl: "/dvd1/AppStream"
       name: "mydvd1"
       description: "yum for docker"
       gpgcheck: no

  - yum_repository:
       baseurl: "/dvd1/BaseOS"
       name: "dvd2"
       description: "myyum dvd2 for package"
       gpgcheck: no
  
  - name: Setting Docker Repo
    yum_repository:
            name: dockername
            description: desc for docker
            baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
            gpgcheck: no

  - name: Installing Docker
    command: "yum install docker-ce --nobest -y"

  - name: Starting Docker
    service:
         name: "docker"
         state: started
         enabled: yes
  
  - name: Installing Docker SDK
    command: "pip3 install docker"


  - name: Pull httpd image
    docker_image:
      name: httpd
      source: pull
  
  - name: Creating html file for httpd
    file:
             path: /webpages
             state: directory
  
  - name: Copying html file  
    copy:
       src: "index.html"
       dest: "/webpage/"

  - name: Running httpd container
    docker_container:
            name: webserver
            image: httpd
            exposed_ports:
                    - "80"
            ports:
                    - "8888:80"
            volumes:
                    - /webpage:/usr/local/apache2/htdocs/
